/*
 * File: app/model/CompanyList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ConnectorTest.model.CompanyList', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'company_id',
                type: 'int'
            },
            {
                name: 'name'
            },
            {
                name: 'ref_ext'
            },
            {
                name: 'zip'
            },
            {
                name: 'town'
            },
            {
                name: 'stcomm_id',
                type: 'int'
            },
            {
                name: 'commercial_status'
            },
            {
                name: 'fk_prospectlevel'
            },
            {
                name: 'categorie'
            },
            {
                name: 'categorie_id'
            },
            {
                name: 'logo_small'
            },
            {
                name: 'code_supplier'
            },
            {
                name: 'code_client'
            }
        ]
    }
});