/*
 * File: app/model/ShipmentList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ConnectorTest.model.ShipmentList', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'ref'
            },
            {
                name: 'ref_ext'
            },
            {
                name: 'supplier_id',
                type: 'int'
            },
            {
                name: 'shipmentstatus_id',
                type: 'int'
            },
            {
                name: 'shipmentstatus'
            },
            {
                name: 'customer_id',
                type: 'int'
            },
            {
                name: 'status'
            },
            {
                name: 'mode'
            },
            {
                dateFormat: 'timestamp',
                name: 'deliver_date',
                type: 'date'
            },
            {
                name: 'qty_toship',
                type: 'float'
            },
            {
                name: 'qty_packaged',
                type: 'float'
            }
        ]
    }
});